openapi: 3.0.2
info:
  description: Return Horse Data
  version: 0.0.1
  title: Horse Database
  
paths:
  /horse:
    post:
      tags:
        - horse
      summary:  add horse
      requestBody:
        description: "Horse object that needs to be added to the store"
        required: true
        content:
          'application/json':
              schema: 
                $ref: '#/components/schemas/Horse'
      responses:
        '200':
          description:  "OK"
          content:
            'application/json':
              schema: 
                $ref: '#/components/schemas/Horse'
        '400':
          description:  "Bad Request"
  /horse/{horseId}:
    get:
      tags:
        - horse
      summary:  return horse 
      parameters:
        - name: horseId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description:  return horse
          content:
            'application/json':
                schema:
                  $ref: '#/components/schemas/Horse'
        '404':
          description:  not found horse
  /race:
    post:
      tags:
        - race
      requestBody:
        description: "Horse object that needs to be added to the store"
        content:
          'application/json':
              schema: 
                $ref: '#/components/schemas/Race'
      responses:
        '200':
          description:  "OK"
          content:
            'application/json':
              schema: 
                $ref: '#/components/schemas/Race'
        '400':
          description:  "Bad Request"
  /race/{raceId}:
    get:
      tags:
        - race
      parameters:
        - name: raceId
          in: path
          required: true
          schema: 
            type: string
      responses:
        '200':
          description:  return horse
          content:
            'application/json':
              schema: 
                $ref: '#/components/schemas/Race'
  /race/{raceId}/{horseId}:
    get:
      tags: 
        - race
      parameters:
        - name: raceId
          in: path
          required: true
          schema: 
            type: string
        - name: horseId
          in: path
          required: true
          schema: 
            type: string
      responses:
        '200':
          description:  'OK'
          content:
            'application/json':
                schema: 
                  $ref: '#/components/schemas/HorseRaceReults'
    post:
      tags:
        - race
      parameters:
        - name: raceId
          in: path
          required: true
          schema: 
            type: string
        - name: horseId
          in: path
          required: true
          schema: 
            type: string
      requestBody:
        description:  "hogehoge"
        content:
          'application/json':
            schema: 
              $ref: '#/components/schemas/HorseRaceReults'
      responses:
        '200':
          description:  return horse result
components:
  schemas:
    Horse:
      type: object
      properties:
        id:
          type: string
          example:  "2017101835"
        name:
          type: string
          example:  "コントレイル"
        age:
          type: integer
          example:  3
        sex:
          type: string
          example:  牡
        trainer:
          type: string
          example:  "矢作 芳人"
        owner:
          type: string
          example:  "前田晋二"
    Race:
      type: object
      properties:
        id: 
          type: string
          example:  "202005021211"
        name: 
          type: string
          example:  "第87回東京優駿(G1)"
        distance:
          type: integer
          example:  2400
        course: 
          type: string
          example:  "東京競馬場" 
        condition:
          type: string
          example:  "良"
        
    HorseRaceReults:
      type: object
      properties:
        raceId:
          type: string
          example:  202005021211
        horseID:
          type: string
          example:  "2017101835"
          # $ref: '#/components/schemas/Horse'
        arrival:
          type: integer
          example:  1
        bracket Number:
          description:  "枠番"
          type: integer
          example : 3
        horse number:
          description:  "馬番"
          type: integer
          example:  5
        weight:
          description: "斤量"
          type: number
          example:  57
        jockey:
          description: "騎手"
          type: string
          example:  "福永祐一"
        time:
          type: string
          example:  "2:24.1"
        difference:
          type: string
          example:  "-"
        pass:
          type: string
          example:  "3-3-5-4"
        last3F:
          type: number
          example:  34.0
        odds:
          description:  "オッズ"
          type: number
          example:  1.4
        order of Favarite Number:
          description:  "人気"
          type: integer
          example:  1
        horse weight:
          description:  "馬体重"
          type: string
          example: "460(-2)"
            
        
      
      
  
  
